name: Sela
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^2.0.0
  http: ^0.12.0+4
  call_number: ^0.0.1
  url_launcher: ^4.2.0+2 
  get_it: ^1.0.3+2
  flutter_open_whatsapp: ^0.1.2
  mailer: ^3.0.4
  
  
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  titled_navigation_bar: ^3.6.0
  line_icons: ^0.2.0
  flutter_circular_chart: ^0.1.0
  google_nav_bar:
#  http: ^0.12.0+4
  build_runner: ^1.0.0
#  json_serializable: ^3.3.0
  json_serializable: ^2.0.0
  provider: ^4.1.1
  
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/1.png
    - lib/assets/images/Logo.png
    - lib/assets/images/home.png
    - lib/assets/images/calendar.png
    - lib/assets/images/layers.png
    - lib/assets/images/user.png
    - lib/assets/images/menuuser.png
    - lib/assets/images/useraccount.png
    - lib/assets/images/logout.png
    - lib/assets/images/sandclock.png
    - lib/assets/images/location.png
    - lib/assets/images/call.png
    - lib/assets/images/teamwork.png
    - lib/assets/images/arrow.png
    - lib/assets/images/whatsapp-3.png
    - lib/assets/images/follow.png
    - lib/assets/images/7gz.png
    - lib/assets/images/c.all.png
    - lib/assets/images/Group 904.png
    - lib/assets/images/Group 887.png
    - lib/assets/images/sand-clock (2).png
    - lib/assets/images/left-arrow (2).png
    - lib/assets/images/sand-clock-6.png
    - lib/assets/images/Path 532.png
    - lib/assets/images/Group 918.png
    - lib/assets/images/email (1).png
    - lib/assets/images/menu.png
    - lib/assets/images/Group 927.png
    - lib/assets/images/Group 926.png
    - lib/assets/images/Group 924.png
    - lib/assets/images/locations.png
    - lib/assets/images/circle1.png


    
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

    - family: ÙArial
      fonts:
        - asset: lib/assets/fonts/Arial.ttf
          weight: 700
    - family: DroidKufi
      fonts:
        - asset: lib/assets/fonts/DroidKufi-Regular.ttf
        - asset: lib/assets/fonts/DroidKufi-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
